# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
# url: 'https://www.nicolaharmanyoga.co.uk'
url: 'https://www.nicolaharmanyoga.co.uk'
baseurl: ''
permalink: pretty
logo: '/assets/images/logo-sitting-96x97.png'
google_analytics: true
phone: 07834070448
email: yoga@nicolaharman.com

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: About
  url: /about/
- title: classes
  url: /classes/
- title: 1-2-1
  url: /one-to-one-sessions/  
- title: sessions
  url: /session-times/
- title: locations
  url: /locations/ 
- title: testimonials
  url: /testimonials/  

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
  testimonials:
    title: Testimonials
    output: true
    description: "Quotes from classes"
    feature_text: 

  
# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: testimonial # Set the default layout for testimonials
  -
    scope:
      path: "assets/images"
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      subtitle: ""
      page_image: ""